### ISSUE TITLE
alpha 1.7.2 full report

### ISSUE THREAD

**Issue by satanKami** [teagan75/Witchery#54]
- returning Annabel - the first part i cant "bring her" by the quest book
- in abbys miska beliver one of them in the wall and he's attacking(and crafing table near the door)
- "cave entrance" is on the start of the road(wolf)
- the den zuleika will attack me before i deside if i help you for prisoners or the gift`
- quest book wont see my talk with zuleika as talked?
- after talking to zuleika and she attacked me anyway emil wont let me tell him i was send to him
- àrgynvostholt enemy near altar will attack but not move
- the gold mine(that the door open)there is no way back...it's blocked
- savid will say what the dark elf will say....took me 30m to understand why he wont talk to me(no dialog)
- living flame will say hello stanger when clicked
- àrgynvostholt everyone attack you as well as sir godfrey
- savid  typo(after interesting he say "the drago not the dragon)
- can st.markovia's thighbone be op weapon to be used against stadv(his castle)
- corpse in strad castle still say hello... how about him sitting next to the coffine saying "hi past me"
- patwickII is lockated in the quest book is 0 0 0 and that is in the middle of the water....
- pidwickII i brought him even he didnt let me bring him and eschar wont be trigger or the quest 
- quest book 225 wont trigger me finding the skull in the skull hall(and im near the chest
book(cause he wont trigger hes speach)
- 228 vladimir wont teach me how to make silver...no dialog on that
- tower ezmeralda wont talk to me..after i got the key`(her first quest need witch armor to be trigger and witch armor is later)
- wizard of wine one of the druid got to move far far away...
- 171 rite of fertility cant be trigger
- 189 izek was killed with vampiric poppet and yet npc quest line say i didnt....as well as the baron
- to kill the baron i need more then 2 bottle of raising reward....maybe 10 will do`
- quest 189 kill izek with vampiric poppet will not open the next quest even if finished
* you need 4.5 vampire poppet to kill izek!!
* note you can disharm npc(could be usefull?)if you choose mage's void

**Comment by teagan75** [comment]
Can I just say ugh lol

**Comment by satanKami** [comment]
amount or misspell?...
and yeah i check everything.....(i still dont know all the paths(like what block who)but i think i handle it pretty nicely

**Comment by teagan75** [comment]
No just the amount of things still wrong lol

**Comment by satanKami** [comment]
well you did switch alot of things
also im about to finish my last line so no more part 1 and 2

also also im trying to work on making lines that more effective... like quest number and stuff... tell me if you liked?

**Comment by teagan75** [comment]
with Annabel, is the problem no location quest in the book or the actual quest not recognizing you have Annabel when you get to her brother?

**Comment by satanKami** [comment]
yes her brother will not notice me having annabel and his questline is closed
as if i never brought her(as well as quest book)
going to sleep its 4am...took a bit too much time to make the report.. night

**Comment by teagan75** [comment]
Good grief! Yes go to bed, but thank you :) 

For next update:
- Annabel should be fixed
- I completely forgot to add a quest in the book between Izek and the Burgomaster kill quests for Fiona's line. I also streamlined the Izek quest so hopefully things will trigger correctly.
- The HIDDEN location is suppose to trigger on the road so the actual quest opens up. What I forgot is to put another location for the mouth of the cave in the actual quest for players.
- Zuleika is not suppose to attack at all even if the faction is low. But if you "rescued" Emil and he attacked and then you didn't kill him, the faction points will not reset to neutral. After you kill Kiril your faction should reset as well. Sometimes even when everything is done correctly custom npcs messes it up. the only way to know what your faction standing is, is in your inventory the tab at the top with the banner. Going to change Zuleika to neutral faction.
- After talkin with Emil, how many times did you click on Sure, going to see if I can streamline his quest a bit so the faction works better. If you use the npc wand on an npc, and click Global and then PlayerData. Click on your name and then faction. Click on the Werewolf faction in the list and delete. That will reset the number to neutral, then try to talk to Zulieka before going to Emil. Oh and hey, I forgot to attach a dialogue to Emil *facepalm*
- seems like you may have been having some sync issues. Not sure why it wouldn't show complete dialogue with Zuleika otherwise
- weird the revenants won't move. I tweaked something so hopefully the won't be paralyzed anymore.
- living flame won't speak anymore
- whoops added a door to get out of the gold mine lol
- everything will attack you in Argyn. Exceptions is Vladimir will only attack if you keep talking to him and he reaches 1 when counting down. I changed Sir Godfrey and his knights to neutral since it seems even when I tell him not to attack he does anyways lol. The mobs should no longer attack once you complete the beacon quest.
- fixed Savid
- the thighbone is suppose to be one of a few weapons you can use against Strahd. He has a lot of health and only is damaged by fire not conventional weapons. It is also given so you can have an easier time with the vampire nest in Vallaki - if you find it before then.
- finally sewed up the corpse's mouth and placed him on the coffin
- have you met Prince Ariel du Plumette yet? :P
- Pidlwick II wouldn't let you soulstone him?
- Fixed the issues with Pidlwick I hope
- For the dragon skull quest. Press L and tell me what is under the tab Ravenloft. Something didn't trigger correctly but everything looks correct. No dialogue should be attached to the chest. The quest is just suppose to complete. The sequence is talk to the dragon spirit, get a secret location quest for the hall, then a secret quest for the chest where its suppose to give the skull.
- Vladimir will only begin the silver quests after the dragon skull/beacon quest is complete
- shortened the leash on the druids
- hopefully rite of fertility will work now
- had a feeling custom npcs wouldn't like passive agressive killing lol. Will need to think that one through. Think I will have a specific drop fall off each of them for the quest to finish. Of course players can cheat unless I completely make them immune to sword and arrow damage hmmmmm lol
- Are you telling me to make Izek easier? lol
- Will give more Brew of Raising as reward - not sure 10 tho lol

**Comment by teagan75** [comment]
- so burgomaster cannot be immune to sword and arrow damage for the zombie attack to work. What I did is if players kill him themselves your faction drops and you instantly become an enemy in town. 
- Izek is immune to conventional weapons so you need to defeat him with poppets or other Witchery. However the guards will attack you if you outwardly attack Izek. Killing guards decreases faction of town. 
- after killing burgomaster in testing I am giving 7 brews of raising as reward cause - dogs lol
- going to change all Kill quests to drops to encourage magic usage

**Comment by satanKami** [comment]
good morning ^_^
- after Zuleika attacked me ive killed kiril but she kept attacked me and emil will not let me rescue him that line is gone even if while she was attacking me i told her ill help to free the prisoners... 
 once i talked to emil i just said one sure and he attacked me(wait falcepalm for me or you? lol)
- yes everyone attacked me except Vladimir and so as well as sir godfrey and his men...so i had to rest them to go near him...and yeah Vladimir didnt attacked me
- ive met.......     Ariel du Plumette  yes i did and she saw me the outside castle.......but i had zivicio :p 
- nope Pidlwick II  will not talk to me
- Vladimir will not begin the silver quests after the dragon skull/beacon quest is complete
- "Are you telling me to make Izek easier? lol"  maybe.....

**Comment by teagan75** [comment]
- Zuleika and Sir Godfrey are now neutral in my dev instance. 
- That reminds me I need to disable the flight on Zvicio armor
- facepalm is for me
- Pidlwick II doesn’t talk. You just grab him and go back to Escher. Pidlwick II is a clockwork doll copy of original

**Comment by satanKami** [comment]
the Zvicio armor no fly no more...can you do it near the end?
ill remind you(im using it to fast travel from one place to another)

**Comment by teagan75** [comment]
I will wait until release to disable the flight hehe
- ok I found the issues with Vladimir and Ezmerelda so they should be fixed next update as well
- abbey isnt finished but the mongrel in the well lives there and will attack those who come close enough.

disarm will help with npcs that have weapons. I would assume any natural resistances will still be in effect.

**Comment by satanKami** [comment]
-werewolf den i think i got what's the problem you lower my faction near zuleika  so i can battle kiril ...so she attack me as well but instand you change it when i need to talk to him like
"sorry i need to kill u cause pretty girl said so"then lower our faction points to add them once we kill him so zuleika  will stop attacking me

**Comment by teagan75** [comment]
I hope this is all fixed in v1.8
