### ISSUE TITLE
Loading Error Alpha 1.7.2 -fix

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Witchery#58]
This is a new instance and game with the the fix for alpha 1.7.2. I noticed I was having some loading chunks errors in places that I have loaded before and when I went back to them the  chunk errors  was occurring in both the overworld and spirit world.  All I had to do was to log out of my game and log back in and the game loaded. Now my game won't load period. The only thing I remember doing new is I expanded my backpack with the pouch ex-pander. 
Attached is my log. 
[latest.log](https://github.com/teagan75/Witchery/files/1938448/latest.log)

Oh, I just want to say.....AWESOME work Teagan. The detail in some of these buildings are fantastic. Did you add some of the Stronghold villages? I know in the spirit world I found one and in the overworld there was one near where the spirit world one was. Is growthcraft suppose to add village changes? I found hops and grape vineyards in them. Never played with growthcraft in it. Pretty neat mod. Love the vineyards in the villages. I didn't know how to set them up.  Another quick question. In the boosting power altar quests, does Essence seeds boost altar power? Does growthcraft seeds?  Love the boosting altar power quest line. It really helps.

**Comment by teagan75** [comment]
I may have to update Difficult Life. Since Mojang took down the old skin servers there have been some issues with older mods. I thought I updated the config file this update to fix some issues but apparently some still exist. I know there is an update for DL. 

The MC villages were generated with the world 😁

I have not tested if growthcraft seeds add anything to the altar. Magic crops seem to add nothing. I know Pam’s Harvestcraft seeds work (not in the pack) and the altar groups all PH seeds as one type, so it may be a similar case with the other mods. Adding more Magic crops or growthcraft plants won’t boost any further. 

You have to run the growthcraft rope between two fence posts. It can be three blocks high. Then you plant a grape seed every three spaces. For hops the ropes also have to hang down from the line so the vine can crawl up. Hops can be planted next to each other. Rice needs special rice paddies.

**Comment by Ladysarajane** [comment]
Love those MC villages. The one in the overworld needs some cleaning up, but they have Witchery books in a stall there.  I love the ideal of a small village trying to protect itself from Stradt ;)
In the spirit world that one village that I found earlier had doubled in size (like it is two villages in one) and it has the vineyards and TWO blacksmiths. I love the guard towers in them.  And then there is a second stronghold village in the spirit world, complete with a coven witch. 
![2018-04-21_22 59 33](https://user-images.githubusercontent.com/34258851/39132429-cfdf0a4a-46df-11e8-8101-a38471abf3f8.png)
![2018-04-22_09 55 32](https://user-images.githubusercontent.com/34258851/39132430-cff32016-46df-11e8-82de-cc01dbb96716.png)
![2018-04-22_09 56 49](https://user-images.githubusercontent.com/34258851/39132432-d04a841e-46df-11e8-8832-3dfc2e844ac3.png)
![2018-04-22_09 58 50](https://user-images.githubusercontent.com/34258851/39132433-d05d013e-46df-11e8-98e4-7306a90fb264.png)

**Comment by teagan75** [comment]
The stronghold villages plus guards is part of Witchery 😁

**Comment by Ladysarajane** [comment]
I never knew that. I like them. And the vineyards showed me how to grow my own wine....LOL

**Comment by Ladysarajane** [comment]
Teagan, It seems this error might be on my side. I CAN'T play any of my games. I have no idea what has changed with twitch or my computer from last night to this morning. All of my games I tried to load are not loading. They all throw errors before I get to the loading screen. Skyfactory 3,  Forever Stranded all of my games do the same thing.

**Comment by Ladysarajane** [comment]
It WAS my side. I updated java last week on my computer and all seemed fine. No problems loading games until this morning. Apparently it caused my video driver to have a meltdown this morning. Updating my driver to the new driver for this java worked. So I am back in. STupid Java updates.
