### ISSUE TITLE
part 1 report 1.8.1

### ISSUE THREAD

**Issue by satanKami** [teagan75/Witchery#62]
* yay no more mining the bone from the coffin maker
- get rid of izek quest by vampiric is a no go since he learn how to not take damage after i took`
so as long as i have the poppet and he's chunkloaded im invisible!!!!
(voodoo mean 1-0 damage everytime... and right now he's 103 )
- izek will respawn at day time
- get rid of izek quest book wont see izek has dead
- i would comment(for fiona watcher) to make it sure she will only talk about necro stuff in the bookclub 
- deathrone the burgomaster the baron will never die!..no really my zombies can't kill him
- fiona has no dialog for wormwod quest
- can't see nikolai watcher in the crystal ball(can see other npcs)(need the alter in the valaki and 600 points)
-  fiora didnt gave any waystone to use on the crystal ball

**Comment by teagan75** [comment]
Fiona is still a work in progress but thanks for the reports. 

I will check on Izek (took his health way down) 
Will also check on Baron but I was sure I killed him. It’s possibly difficult life scaling their health too high. May have to disable that.

**Comment by satanKami** [comment]
i chanced izek's health to 1 and he got 42 health...
always going to the routs i know it's not 100% complete
once everything is good i'll try every option

**Comment by teagan75** [comment]
Thanks 😁 And the health increase seems random but I will change him to 1 health and the baron if I have no other choice. 

Also all the npcs respawn now to make it multiplayer friendly. AreaKill doesn’t always work especially if one dies and the other gets the kill. I don’t like it because it isn’t very immersive but what can I do hehe

**Comment by satanKami** [comment]
- fiora watcher finding baba yaga (no waystone reward given) and after summoning babayaga with the crystal ball and killing her the quest still wont be finished-edit:it's location...but the baba yaga tree has no trigger)

**Comment by satanKami** [comment]
added to old line

**Comment by teagan75** [comment]
> 1.  yay no more mining the bone from the coffin maker

> 2. get rid of izek quest by vampiric is a no go since he learn how to not take damage after i took`

>  so as long as i have the poppet and he's chunkloaded im invisible!!!!

> (voodoo mean 1-0 damage everytime... and right now he's 103 )

> 3. izek will respawn at day time

> 4. get rid of izek quest book wont see izek has dead

> 5. i would comment(for fiona watcher) to make it sure she will only talk about necro stuff in the 
    bookclub

> 6. deathrone the burgomaster the baron will never die!..no really my zombies can't kill him

> 7. fiona has no dialog for wormwod quest

> 8. can't see nikolai watcher in the crystal ball(can see other npcs)(need the alter in the valaki and 600 
  
> points)

> 9. fiora didnt gave any waystone to use on the crystal ball

 
1. Yay! Part of the multiplayer update
2. I took away Izek's god powers and changed his health  :D
3. Part of the multiplayer update
4. Did you grab the journal from him? Custom NPCs won't register the kill unless you are close so I changed it to a drop. edit: Going to change it back to an AreaKill now that the health issue has been dealt with.
5. You mean let players know she will only talk necro in her lair?
6. I took the Baron's health down. He has no other resistences.
7. She doesn't need a dialogue for wormwood. You get that quest right after Blood Rose
8. I put an altar in Fiona's lair. Also you see through Nikolai's eyes. You also have to hold right-click down to keep looking. I will make a note of this.
9. Added waystone to quest for next update.

**Comment by satanKami** [comment]
8. correction i can see him but need to be in vallaki
11. nooo!! lol my god is dead(btw where is izek's room?)
14.yes it will be less confusing since she wont talk to you above the club room 
something like welcome to my club plz keep the stuff we learn only in here...or something?
yay! 
19. i forgot to say somehow valaki vistini camp potion guy didnt work for me.. maybe order or something?
edit: ill re add and remove old post and repost it

**Comment by satanKami** [comment]
1- pickpocket quest wont let me talk to ezmerelda but talking head works(in quest book)
2- i didnt warm anyone from yan but somehow it work...
3- sunlight catcher quest suddenly appear  
4- the potion maker in vistani near valaki need just gunpowder not anything else
5- the potion with wooden ash wont work? order isn't good?
6- abby i found ezmerelda and i told her i can to check on abbot....i never got a mission to look on it the storyline messed up
7- krezek baron dimitri missing his line 
8- krezek baron missing his gravedigging and that mission has no before that mission
9- something old quest location not there...
10- near amber temple and the pass there is a glass floating in the air
11- the amber temple sparks say hi stanger
12- argynvostholt ezmelda will give me another key to the tower but in valaki i'll get a key anyway...
(stealing key or getting it at valaki)
13-  phantom warrior blocking the way and will attack(does killing is the only way?)
(this is a question not a problem) 
14- sir godfrey gwilym will talk to me even if i didn't talk to vlad first
15- savid's potion somehow different also it dosent say what potion throw or stronger
16- anti-werewolf potion quest from vlad wont be trigger cause it's missing from vlad
17- iiya body's(krezek) is too invisible to be noticed 
18- something blue mission you can't see sergi and his text so it's hard to notice where he is(maybe bigger test let us see him?
19- prison key quest pop up without me talking to the wolf den
i think this is all i can say in this update...
bit sick so ill check if there isn't anything else

p.s is adding numbers make it easy?
i want to make reports as easy as possible for you so please tell me the best version you want to get

**Comment by teagan75** [comment]
I do numbers to keep track myself when I am correcting mistakes.  It doesn’t matter if you use bullets or numbers 😁

**Comment by teagan75** [comment]
1. If you chose to pickpoket or chose that dialogue path, the only way to get Ezmerelda's quest is by Argynvostholt. I may add it to her char in the abbey too.
2. It didn't auto complete. You probably talked to Arrigal but I forgot to write a closing for the quest so it seemed like an autocomplete hehe
3. Sunlight catcher is suppose to be there but I need to make it multiplayer friendly.
4. I don't understand this one. Which potion is the issue?
5. There are a few potions that require wood ash
6. Ezmerelda in the abbey has no quest atm
7. fixed for next update
8. fixed for next update
9. fixed for next update
10. Wonder how that got there lol. removed for next update
11. They will speak so I am not sure what they will say yet.
12. I did that so if players came here first they could still get the key.
13. meant to be that way
14. fixed for next update
15. Savid's potion is found in the mansion in an npc chest. you don't have to make it. I checked the potions and they have the same id.
16. no its attached but gated behind the custom brews. made it a requirement in the quest book for next update
17. Meant to be invisible because it is not representing an npc but a grave site.
18. If you place Ireena by the wolf altar at the fountain, the chat will show the conversation between them. Did the conversation not start? He is semi visible in the water. he is a ghost after all lol
19. Prison key will pop up as a result of him talking to you. One option he kills you the other if you visit his mate first will be the peaceful one
Note: Baba Yaga isn't really a questline since she is a mob. I could have the questbook ask for her hat but that would be the same drop rate as the Huntsman's spear. The book is in the house AND I need to change that to be multiplayer friendly :D

Hope you feel better! Rest up :D

**Comment by satanKami** [comment]
12+1. well normally if i talk to victor and keep his promise i would talk to her in the tower and get the questline?
what im trying to say is the key to the tower can be received by 3 ways and since vallaki is something everyone will do getting a key in Argynvostholt seems unneeded?... since her line is about finding her master
i didnt got a new mission in Argynvostholt's  Ezmerelda ...
3.well it is empty quest so very friendly?
4. the second potion i tied to make but somehow it didn't i'll give it a try again later
6. there is no quest but what they character say in there is breaking the storyline
11. will they tell you? will they say what i've done?
15. opps i was thinking i had to make it...
17.so why not putting the npc on the grave?they can be placed on the grave itself
18.it did start but i didnt saw his dialog or him at all i had to use the npc wand to notice where he was

i will never Rest!!
cause i have tons of work need to be done if i want to finish my semester ....
uni life is too fast.....

**Comment by teagan75** [comment]
1+12 Will look at changing Ezmerelda 
3. Suncatcher is removed and an npc is there to give you the quest item
4. Potion quests changes didn’t save properly 
6. She just tells you about the Abbot and her mission. It’s part of the D&D story for her
11. No spoilers hehe
17. The corpse has already been buried and you are grave digging. I use invisible npcs a lot especially in Fallcraft and Tolkiencraft when an npc model is not available. 
18. I made Sergei more visible and put a note where to find him. 

Yes uni is a busy time but you still need rest hehe

**Comment by teagan75** [comment]
Ok I removed the key from Exmerelda at Argyn. To clarify her conversation at the abbey, if you have done her quests at the tower she will call you a friend at the abbey. If you have not met her and done her quests, she will call you stranger. Does that help?

**Comment by satanKami** [comment]
makes more sense yay ^_^

**Comment by teagan75** [comment]
fixed in v1.8.1
