### ISSUE TITLE
Fixes...Not an issue just a comment on 1.8.1

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Witchery#70]
Just wanted to let you know that so far in playing the 1.8.1 everything seems to be fixed in the early stages of Barovia. My brother had eye surgery, so I haven't been on it as much as I wanted to be. In entering Barovia from spawn, I encountered a Wolf and when hitting him he had 300 hit points needless to see he slaughtered me. I had to double check my settings and they were correct...it was just a fluke, rest of the wolves  were fine. Kolyana gate was fine....it was locked. I'm even getting zombie spawns in the death house now and around Barovia. I found a zombie spawner in the hills, so zombie flesh isn't an issue for me this time around. Teagan this game is amazing and fun. I love watching Christa, Hailee and HeatherReneeB trying out this pack. POOR Christa!! Not sure why they are not getting bat spawns in their house. They are past the point where mine start spawning.

**Comment by teagan75** [comment]
They weren’t getting bats because command blocks aren’t enabled on servers by default. Since I haven’t made a proper server file yet I forgot lol. 

Sorry about your brother and hope he has a speedy recovery. Glad you are enjoying the pack and watching the others. It’s certainly been a labor of love. Stay tuned for another couple of squad members playing it in the near future 😁

**Comment by Ladysarajane** [comment]
I hope Modii is one. The death house will kill him! Lol!

**Comment by Ladysarajane** [comment]
My wish came true!
He had the same thing with the beginning wolf being high in hit points.

**Comment by teagan75** [comment]
Maybe I should find that wolf and kill him before the next update lol
