### ISSUE TITLE
finding the daughter 

### ISSUE THREAD

**Issue by satanKami** [teagan75/Witchery#74]
something i've noticed from modii's video is once you finish the puppets people will try to talk to marry
the quest need to be locked until you start with the ireana quest cause after you talk to father about more information you get another dialog

**Comment by teagan75** [comment]
Finding Gertruda should be locked behind the altar dialogues

**Comment by satanKami** [comment]
well it doesn't look like it when modii played it something i didn't thought about

**Comment by Ladysarajane** [comment]
Modii really didn't  look at the Better Questing Book thoroughly.  He is OCD and wants to complete that quest line. I did see on it though he had the Tavern of Blood Vine quest line that would lead him to Ireena then the Church and then after being at the Church, Mary will get talky again. He just has to look at the quest book a little better. :)

**Comment by teagan75** [comment]
I see. Finally watched the vid. I really seriously thought I had that quest gates in the BQ book lol. This pack has been challenging lol

**Comment by Ladysarajane** [comment]
Yeah he has tunnel vision on that quest book. He wants to make it linear. He is going to find out that these quests are not linear...LOL that is why I wanted Modii to play this and he doesn't disappoint! I saw Snoop787 being mobbed by dogs, and saw his difficulty level of Ha Ha High and Almost fell off my chair laughing cause I just knew he had the server running all that time after he set it up. Need some kind of warning to server players/owners for this when it comes out. Glad you where able to fix it for him. Not sure what to do with Mary to get people to see other quests after the poppets. I don't know if you remember, but I brought this up about the abruptness of this. You did change Mary kicking people out of her house to earlier instead of after the poppets. I cannot think of of a way to add something to Mary to get people to "move" on after the poppet quest, that won't affect the poppets.

**Comment by teagan75** [comment]
The poppets have certainly been a PITA. As far as the difficulty level progressing on servers, the dev of Difficult Life was supposed to fix that - guess not.

**Comment by satanKami** [comment]
the ideal of this problem that other people reported as well after puppets the quest look open 
so people try to keep the line without going to the other line
can't you make it unlock only after father quest ? to make it much more simple to understand

**Comment by Ladysarajane** [comment]
Thought Teagan, don't know if it is possible or not at this point in time....maybe after the poppet quest and before the Gertruda quest, maybe an informational Better Questing quest, saying something Like "Mary seems to only want to talk of poppets now, maybe I should explore other places in the town of Barovia" and all you do is click the box understand you read it. You wouldn't have to give a reward, but if you did, maybe more magical fertilizer? (Hee hee or maybe a storage drawer controller?)  That way you are not messing with NPC's quest log.

**Comment by satanKami** [comment]
simple change the quest to be unlock by 2 complete quest and it will be
locked till you finished what you had to do

**Comment by teagan75** [comment]
this will be fixed in the next update
