### ISSUE TITLE
report on  1.8.1

### ISSUE THREAD

**Issue by satanKami** [teagan75/Witchery#78]
-amber temple second floor not ready
-sparks in temple still talk
-krezk quest to enter the city has no trigger
-krezek quest ak for unamed barrel but the winery give me named item beer keg
-wolf den kiril will respawn
-wolf den i've free them and all they say is hi stranger?
-wolf den has no altar mean( 0 power)
-yan in the tower quest still increase your points 
`-azmerelda d" avenir quest in the book won't be trigger when talk to in argynvostholt or in the tower
but the npc will talk to you and quest the things
sorry i took so long to report

**Comment by teagan75** [comment]
- Will begin finishing up Yester Hill and Amber Temple (including fixinng the sparks)
- Krezk quest should be fixed now
- I go back and forth with respawns. I know it breaks immersion but if there is a glitch there needs to be a way to complete the kill quest. Maybe I should just provide a clone list.
- the wolf den doesn't need an altar anymore. I have tested the alternate way to get bit and it does work despite people saying it doesn't hehe. So that is what the wolf circle on top of the den is for now. A wolf altar is there with a wolf trap and a place to tie up the sheep.
- Yan should be fixed
- Ezmerelda trigger will work now

All of this will be in next update (except Yester Hill and Amber Temple).

And I am sorry it's taking me so long to finish this pack hehe

**Comment by teagan75** [comment]
update 1.8.2 has been pushed to Curse

**Comment by teagan75** [comment]
FYI I am currently working on Fate of Gods again. It will be a 1.12 pack since Advent of Ascension is updating to 1.12 I am redoing alot but hope it will be better than ever :)

**Comment by satanKami** [comment]
im happy to hear the good news 
if you ever need another beta testing im here ^_^
