### ISSUE TITLE
Map Error

### ISSUE THREAD

**Issue by MountainTroll** [teagan75/Witchery#79]
I don't think this is a problem with the modpack, but how do you set the map? It won't download the map into any existing worlds. Please help!

**Comment by teagan75** [comment]
This happens sometimes. Take the template folder in your instance/.minecraft folder and place it in your saves folder

**Comment by MountainTroll** [comment]
The map loaded, but now in the little quests tan of inv, it says I don't have any quests, although when I walked to the village, it said I completed a quest.

**Comment by teagan75** [comment]
Are you pressing the ~ key

**Comment by MountainTroll** [comment]
I did, pulled up quests, but then when I went down the gravel path, on my screen it shows I completed, but I go to quests and it won't let me click the complete quest/check quest button.

**Comment by teagan75** [comment]
The quest is already green meaning complete right? There is nothing to check. The next quest should open

**Comment by MountainTroll** [comment]
Yes, but the problem is, it won't check off, event though I've done it.

**Comment by teagan75** [comment]
Can you show me a screenshot?

**Comment by MountainTroll** [comment]
Don't know how, but it just looks like an uncompleted quest.

**Comment by Ladysarajane** [comment]
The first quest that completes is the startup quest. That is not in the quest book. The second one is the 'Where Am I?'  quest as you enter Barovia. That will complete turn green in the book, but there is no reward. The other two quests will open. Your book should look like this:
![2018-08-23_21 25 06](https://user-images.githubusercontent.com/34258851/44560023-8c069f80-a71b-11e8-89bc-8cf9b048d57d.png)

The yellow lines will blink if the next quest is opened. I believe to take a screenshot is F2. It is saved in your instance file if you are using twitch.  
Be aware there are 2 quest books. The Better Questing book and the second one is the NPC quest Log. 
I found that I had to look for quest log in controls and rebind it to another key in order to access it.

**Comment by MountainTroll** [comment]
The bug is, that quest shows completed when I enter the village, but I pull up the quests and it is not completed.

**Comment by teagan75** [comment]
Can u run the command /bq_admin edit 
Check what the chat says. If it says edit is off that was the issue. If it says edit on run the command again

**Comment by Ladysarajane** [comment]
There is another quest that is close to that one that might say completed. Use the coordinates in the quest book to find the exact spot. The quest that may have sounded is the Burgermister House.

**Comment by teagan75** [comment]
Reopen this if you need more help.
