### ISSUE TITLE
any updates to make the pack playable again?

### ISSUE THREAD

**Issue by niemandvs** [teagan75/Witchery#86]
Hi i am new and i like to learn more over witchery but when i download the mod pack it has any mods in and i try it again download the zip data but again not the mods i think it shoud have in because there is no witchery in my zip data so now i hope you maybe find the issus and hope i can play the pack one day by my one but for solonge i try to learn how witchery works over your playing it self on yt. but i think you know make things by the own is more learning than watching it.
sorry for my bad english.

**Comment by teagan75** [comment]
You have to use the Twitch launcher to run any Curse modpacks

**Comment by niemandvs** [comment]
i know this but if i do that i have there no mods in the downloaded profil

**Comment by teagan75** [comment]
So you have downloaded the launcher from here? https://www.twitch.tv/downloads I am confused because you talk about a zip file. The zip file on CurseForge is only a placeholder and has no mods

**Comment by niemandvs** [comment]
yes i download a zip fill of the modpack from https://www.curseforge.com/minecraft/modpacks/teagans-guide-to-witchery/files/2627085 and put it in the twitch launcher because the instance of the pack in the folder instance under .../twitch/minecraft/ but it dont helps also i just make a short video for you on my twitch channel niemand_vs so you can see what happend when i download it directly over twitchlauncher

**Comment by teagan75** [comment]
you cannot use the zip file from curseforge. It is data used by the Twitch
launcher. From what I could see it was taking a long time to install and
you tried to launch the game before the launcher was finished installing.
It sometimes takes a long time to start and finish. I was able to install
the pack just now. I can't help with this since it is a launcher issue and
not a pack issue. You would need to open a support ticket with Twitch.
